# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xion/mint/v1/genesis.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'xion/mint/v1/genesis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from xion.mint.v1 import mint_pb2 as xion_dot_mint_dot_v1_dot_mint__pb2
from amino import amino_pb2 as amino_dot_amino__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1axion/mint/v1/genesis.proto\x12\x0cxion.mint.v1\x1a\x14gogoproto/gogo.proto\x1a\x17xion/mint/v1/mint.proto\x1a\x11\x61mino/amino.proto\"\x80\x01\n\x0cGenesisState\x12\x37\n\x06minter\x18\x01 \x01(\x0b\x32\x14.xion.mint.v1.MinterB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06minter\x12\x37\n\x06params\x18\x02 \x01(\x0b\x32\x14.xion.mint.v1.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06paramsB\x9b\x01\n\x10\x63om.xion.mint.v1B\x0cGenesisProtoP\x01Z\'github.com/burnt-labs/xion/x/mint/types\xa2\x02\x03XMX\xaa\x02\x0cXion.Mint.V1\xca\x02\x0cXion\\Mint\\V1\xe2\x02\x18Xion\\Mint\\V1\\GPBMetadata\xea\x02\x0eXion::Mint::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xion.mint.v1.genesis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.xion.mint.v1B\014GenesisProtoP\001Z\'github.com/burnt-labs/xion/x/mint/types\242\002\003XMX\252\002\014Xion.Mint.V1\312\002\014Xion\\Mint\\V1\342\002\030Xion\\Mint\\V1\\GPBMetadata\352\002\016Xion::Mint::V1'
  _globals['_GENESISSTATE'].fields_by_name['minter']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['minter']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_GENESISSTATE'].fields_by_name['params']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_GENESISSTATE']._serialized_start=111
  _globals['_GENESISSTATE']._serialized_end=239
# @@protoc_insertion_point(module_scope)
