# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xion/mint/v1/event.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'xion/mint/v1/event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18xion/mint/v1/event.proto\x12\x0cxion.mint.v1\x1a\x14gogoproto/gogo.proto\"\xf4\x03\n\x13MintIncentiveTokens\x12h\n\x0c\x62onded_ratio\x18\x01 \x01(\tBE\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xf2\xde\x1f\x13yaml:\"bonded_ratio\"R\x0b\x62ondedRatio\x12`\n\tinflation\x18\x02 \x01(\tBB\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xf2\xde\x1f\x10yaml:\"inflation\"R\tinflation\x12w\n\x11\x61nnual_provisions\x18\x03 \x01(\tBJ\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xf2\xde\x1f\x18yaml:\"annual_provisions\"R\x10\x61nnualProvisions\x12#\n\rneeded_amount\x18\x04 \x01(\x04R\x0cneededAmount\x12)\n\x10\x63ollected_amount\x18\x05 \x01(\x04R\x0f\x63ollectedAmount\x12#\n\rminted_amount\x18\x06 \x01(\x04R\x0cmintedAmount\x12#\n\rburned_amount\x18\x07 \x01(\x04R\x0c\x62urnedAmountB\x99\x01\n\x10\x63om.xion.mint.v1B\nEventProtoP\x01Z\'github.com/burnt-labs/xion/x/mint/types\xa2\x02\x03XMX\xaa\x02\x0cXion.Mint.V1\xca\x02\x0cXion\\Mint\\V1\xe2\x02\x18Xion\\Mint\\V1\\GPBMetadata\xea\x02\x0eXion::Mint::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xion.mint.v1.event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.xion.mint.v1B\nEventProtoP\001Z\'github.com/burnt-labs/xion/x/mint/types\242\002\003XMX\252\002\014Xion.Mint.V1\312\002\014Xion\\Mint\\V1\342\002\030Xion\\Mint\\V1\\GPBMetadata\352\002\016Xion::Mint::V1'
  _globals['_MINTINCENTIVETOKENS'].fields_by_name['bonded_ratio']._loaded_options = None
  _globals['_MINTINCENTIVETOKENS'].fields_by_name['bonded_ratio']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\362\336\037\023yaml:\"bonded_ratio\"'
  _globals['_MINTINCENTIVETOKENS'].fields_by_name['inflation']._loaded_options = None
  _globals['_MINTINCENTIVETOKENS'].fields_by_name['inflation']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\362\336\037\020yaml:\"inflation\"'
  _globals['_MINTINCENTIVETOKENS'].fields_by_name['annual_provisions']._loaded_options = None
  _globals['_MINTINCENTIVETOKENS'].fields_by_name['annual_provisions']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\362\336\037\030yaml:\"annual_provisions\"'
  _globals['_MINTINCENTIVETOKENS']._serialized_start=65
  _globals['_MINTINCENTIVETOKENS']._serialized_end=565
# @@protoc_insertion_point(module_scope)
