# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xion/mint/v1/query.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'xion/mint/v1/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from xion.mint.v1 import mint_pb2 as xion_dot_mint_dot_v1_dot_mint__pb2
from amino import amino_pb2 as amino_dot_amino__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18xion/mint/v1/query.proto\x12\x0cxion.mint.v1\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17xion/mint/v1/mint.proto\x1a\x11\x61mino/amino.proto\"\x14\n\x12QueryParamsRequest\"N\n\x13QueryParamsResponse\x12\x37\n\x06params\x18\x01 \x01(\x0b\x32\x14.xion.mint.v1.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params\"\x17\n\x15QueryInflationRequest\"k\n\x16QueryInflationResponse\x12Q\n\tinflation\x18\x01 \x01(\x0c\x42\x33\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xa8\xe7\xb0*\x01R\tinflation\"\x1e\n\x1cQueryAnnualProvisionsRequest\"\x81\x01\n\x1dQueryAnnualProvisionsResponse\x12`\n\x11\x61nnual_provisions\x18\x01 \x01(\x0c\x42\x33\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xa8\xe7\xb0*\x01R\x10\x61nnualProvisions2\x84\x03\n\x05Query\x12k\n\x06Params\x12 .xion.mint.v1.QueryParamsRequest\x1a!.xion.mint.v1.QueryParamsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/xion/mint/v1/params\x12w\n\tInflation\x12#.xion.mint.v1.QueryInflationRequest\x1a$.xion.mint.v1.QueryInflationResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/xion/mint/v1/inflation\x12\x94\x01\n\x10\x41nnualProvisions\x12*.xion.mint.v1.QueryAnnualProvisionsRequest\x1a+.xion.mint.v1.QueryAnnualProvisionsResponse\"\'\x82\xd3\xe4\x93\x02!\x12\x1f/xion/mint/v1/annual_provisionsB\x99\x01\n\x10\x63om.xion.mint.v1B\nQueryProtoP\x01Z\'github.com/burnt-labs/xion/x/mint/types\xa2\x02\x03XMX\xaa\x02\x0cXion.Mint.V1\xca\x02\x0cXion\\Mint\\V1\xe2\x02\x18Xion\\Mint\\V1\\GPBMetadata\xea\x02\x0eXion::Mint::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xion.mint.v1.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.xion.mint.v1B\nQueryProtoP\001Z\'github.com/burnt-labs/xion/x/mint/types\242\002\003XMX\252\002\014Xion.Mint.V1\312\002\014Xion\\Mint\\V1\342\002\030Xion\\Mint\\V1\\GPBMetadata\352\002\016Xion::Mint::V1'
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._loaded_options = None
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_QUERYINFLATIONRESPONSE'].fields_by_name['inflation']._loaded_options = None
  _globals['_QUERYINFLATIONRESPONSE'].fields_by_name['inflation']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\250\347\260*\001'
  _globals['_QUERYANNUALPROVISIONSRESPONSE'].fields_by_name['annual_provisions']._loaded_options = None
  _globals['_QUERYANNUALPROVISIONSRESPONSE'].fields_by_name['annual_provisions']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\250\347\260*\001'
  _globals['_QUERY'].methods_by_name['Params']._loaded_options = None
  _globals['_QUERY'].methods_by_name['Params']._serialized_options = b'\202\323\344\223\002\026\022\024/xion/mint/v1/params'
  _globals['_QUERY'].methods_by_name['Inflation']._loaded_options = None
  _globals['_QUERY'].methods_by_name['Inflation']._serialized_options = b'\202\323\344\223\002\031\022\027/xion/mint/v1/inflation'
  _globals['_QUERY'].methods_by_name['AnnualProvisions']._loaded_options = None
  _globals['_QUERY'].methods_by_name['AnnualProvisions']._serialized_options = b'\202\323\344\223\002!\022\037/xion/mint/v1/annual_provisions'
  _globals['_QUERYPARAMSREQUEST']._serialized_start=138
  _globals['_QUERYPARAMSREQUEST']._serialized_end=158
  _globals['_QUERYPARAMSRESPONSE']._serialized_start=160
  _globals['_QUERYPARAMSRESPONSE']._serialized_end=238
  _globals['_QUERYINFLATIONREQUEST']._serialized_start=240
  _globals['_QUERYINFLATIONREQUEST']._serialized_end=263
  _globals['_QUERYINFLATIONRESPONSE']._serialized_start=265
  _globals['_QUERYINFLATIONRESPONSE']._serialized_end=372
  _globals['_QUERYANNUALPROVISIONSREQUEST']._serialized_start=374
  _globals['_QUERYANNUALPROVISIONSREQUEST']._serialized_end=404
  _globals['_QUERYANNUALPROVISIONSRESPONSE']._serialized_start=407
  _globals['_QUERYANNUALPROVISIONSRESPONSE']._serialized_end=536
  _globals['_QUERY']._serialized_start=539
  _globals['_QUERY']._serialized_end=927
# @@protoc_insertion_point(module_scope)
