# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xion/jwk/v1/genesis.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'xion/jwk/v1/genesis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from xion.jwk.v1 import params_pb2 as xion_dot_jwk_dot_v1_dot_params__pb2
from xion.jwk.v1 import audience_pb2 as xion_dot_jwk_dot_v1_dot_audience__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19xion/jwk/v1/genesis.proto\x12\x0bxion.jwk.v1\x1a\x14gogoproto/gogo.proto\x1a\x18xion/jwk/v1/params.proto\x1a\x1axion/jwk/v1/audience.proto\"\x82\x01\n\x0cGenesisState\x12\x31\n\x06params\x18\x01 \x01(\x0b\x32\x13.xion.jwk.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params\x12?\n\x0c\x61udienceList\x18\x02 \x03(\x0b\x32\x15.xion.jwk.v1.AudienceB\x04\xc8\xde\x1f\x00R\x0c\x61udienceListB\x95\x01\n\x0f\x63om.xion.jwk.v1B\x0cGenesisProtoP\x01Z&github.com/burnt-labs/xion/x/jwk/types\xa2\x02\x03XJX\xaa\x02\x0bXion.Jwk.V1\xca\x02\x0bXion\\Jwk\\V1\xe2\x02\x17Xion\\Jwk\\V1\\GPBMetadata\xea\x02\rXion::Jwk::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xion.jwk.v1.genesis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017com.xion.jwk.v1B\014GenesisProtoP\001Z&github.com/burnt-labs/xion/x/jwk/types\242\002\003XJX\252\002\013Xion.Jwk.V1\312\002\013Xion\\Jwk\\V1\342\002\027Xion\\Jwk\\V1\\GPBMetadata\352\002\rXion::Jwk::V1'
  _globals['_GENESISSTATE'].fields_by_name['params']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['params']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['audienceList']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['audienceList']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE']._serialized_start=119
  _globals['_GENESISSTATE']._serialized_end=249
# @@protoc_insertion_point(module_scope)
