# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xion/v1/feegrant.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'xion/v1/feegrant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from amino import amino_pb2 as amino_dot_amino__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16xion/v1/feegrant.proto\x12\x07xion.v1\x1a\x14gogoproto/gogo.proto\x1a\x19google/protobuf/any.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a\x11\x61mino/amino.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xf5\x01\n\x0e\x41uthzAllowance\x12]\n\tallowance\x18\x01 \x01(\x0b\x32\x14.google.protobuf.AnyB)\xca\xb4-%cosmos.feegrant.v1beta1.FeeAllowanceIR\tallowance\x12=\n\rauthz_grantee\x18\x02 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\x0c\x61uthzGrantee:E\x88\xa0\x1f\x00\xca\xb4-%cosmos.feegrant.v1beta1.FeeAllowanceI\x8a\xe7\xb0*\x13xion/AuthzAllowance\"\x87\x02\n\x12\x43ontractsAllowance\x12]\n\tallowance\x18\x01 \x01(\x0b\x32\x14.google.protobuf.AnyB)\xca\xb4-%cosmos.feegrant.v1beta1.FeeAllowanceIR\tallowance\x12G\n\x12\x63ontract_addresses\x18\x02 \x03(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\x11\x63ontractAddresses:I\x88\xa0\x1f\x00\xca\xb4-%cosmos.feegrant.v1beta1.FeeAllowanceI\x8a\xe7\xb0*\x17xion/ContractsAllowance\"\xbe\x01\n\x11MultiAnyAllowance\x12_\n\nallowances\x18\x01 \x03(\x0b\x32\x14.google.protobuf.AnyB)\xca\xb4-%cosmos.feegrant.v1beta1.FeeAllowanceIR\nallowances:H\x88\xa0\x1f\x00\xca\xb4-%cosmos.feegrant.v1beta1.FeeAllowanceI\x8a\xe7\xb0*\x16xion/MultiAnyAllowanceB\x82\x01\n\x0b\x63om.xion.v1B\rFeegrantProtoP\x01Z\'github.com/burnt-labs/xion/x/xion/types\xa2\x02\x03XXX\xaa\x02\x07Xion.V1\xca\x02\x07Xion\\V1\xe2\x02\x13Xion\\V1\\GPBMetadata\xea\x02\x08Xion::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xion.v1.feegrant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.xion.v1B\rFeegrantProtoP\001Z\'github.com/burnt-labs/xion/x/xion/types\242\002\003XXX\252\002\007Xion.V1\312\002\007Xion\\V1\342\002\023Xion\\V1\\GPBMetadata\352\002\010Xion::V1'
  _globals['_AUTHZALLOWANCE'].fields_by_name['allowance']._loaded_options = None
  _globals['_AUTHZALLOWANCE'].fields_by_name['allowance']._serialized_options = b'\312\264-%cosmos.feegrant.v1beta1.FeeAllowanceI'
  _globals['_AUTHZALLOWANCE'].fields_by_name['authz_grantee']._loaded_options = None
  _globals['_AUTHZALLOWANCE'].fields_by_name['authz_grantee']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_AUTHZALLOWANCE']._loaded_options = None
  _globals['_AUTHZALLOWANCE']._serialized_options = b'\210\240\037\000\312\264-%cosmos.feegrant.v1beta1.FeeAllowanceI\212\347\260*\023xion/AuthzAllowance'
  _globals['_CONTRACTSALLOWANCE'].fields_by_name['allowance']._loaded_options = None
  _globals['_CONTRACTSALLOWANCE'].fields_by_name['allowance']._serialized_options = b'\312\264-%cosmos.feegrant.v1beta1.FeeAllowanceI'
  _globals['_CONTRACTSALLOWANCE'].fields_by_name['contract_addresses']._loaded_options = None
  _globals['_CONTRACTSALLOWANCE'].fields_by_name['contract_addresses']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_CONTRACTSALLOWANCE']._loaded_options = None
  _globals['_CONTRACTSALLOWANCE']._serialized_options = b'\210\240\037\000\312\264-%cosmos.feegrant.v1beta1.FeeAllowanceI\212\347\260*\027xion/ContractsAllowance'
  _globals['_MULTIANYALLOWANCE'].fields_by_name['allowances']._loaded_options = None
  _globals['_MULTIANYALLOWANCE'].fields_by_name['allowances']._serialized_options = b'\312\264-%cosmos.feegrant.v1beta1.FeeAllowanceI'
  _globals['_MULTIANYALLOWANCE']._loaded_options = None
  _globals['_MULTIANYALLOWANCE']._serialized_options = b'\210\240\037\000\312\264-%cosmos.feegrant.v1beta1.FeeAllowanceI\212\347\260*\026xion/MultiAnyAllowance'
  _globals['_AUTHZALLOWANCE']._serialized_start=228
  _globals['_AUTHZALLOWANCE']._serialized_end=473
  _globals['_CONTRACTSALLOWANCE']._serialized_start=476
  _globals['_CONTRACTSALLOWANCE']._serialized_end=739
  _globals['_MULTIANYALLOWANCE']._serialized_start=742
  _globals['_MULTIANYALLOWANCE']._serialized_end=932
# @@protoc_insertion_point(module_scope)
