# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from xion.v1 import query_pb2 as xion_dot_v1_dot_query__pb2


class QueryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WebAuthNVerifyRegister = channel.unary_unary(
                '/xion.v1.Query/WebAuthNVerifyRegister',
                request_serializer=xion_dot_v1_dot_query__pb2.QueryWebAuthNVerifyRegisterRequest.SerializeToString,
                response_deserializer=xion_dot_v1_dot_query__pb2.QueryWebAuthNVerifyRegisterResponse.FromString,
                _registered_method=True)
        self.WebAuthNVerifyAuthenticate = channel.unary_unary(
                '/xion.v1.Query/WebAuthNVerifyAuthenticate',
                request_serializer=xion_dot_v1_dot_query__pb2.QueryWebAuthNVerifyAuthenticateRequest.SerializeToString,
                response_deserializer=xion_dot_v1_dot_query__pb2.QueryWebAuthNVerifyAuthenticateResponse.FromString,
                _registered_method=True)


class QueryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WebAuthNVerifyRegister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WebAuthNVerifyAuthenticate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WebAuthNVerifyRegister': grpc.unary_unary_rpc_method_handler(
                    servicer.WebAuthNVerifyRegister,
                    request_deserializer=xion_dot_v1_dot_query__pb2.QueryWebAuthNVerifyRegisterRequest.FromString,
                    response_serializer=xion_dot_v1_dot_query__pb2.QueryWebAuthNVerifyRegisterResponse.SerializeToString,
            ),
            'WebAuthNVerifyAuthenticate': grpc.unary_unary_rpc_method_handler(
                    servicer.WebAuthNVerifyAuthenticate,
                    request_deserializer=xion_dot_v1_dot_query__pb2.QueryWebAuthNVerifyAuthenticateRequest.FromString,
                    response_serializer=xion_dot_v1_dot_query__pb2.QueryWebAuthNVerifyAuthenticateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xion.v1.Query', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xion.v1.Query', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Query(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WebAuthNVerifyRegister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xion.v1.Query/WebAuthNVerifyRegister',
            xion_dot_v1_dot_query__pb2.QueryWebAuthNVerifyRegisterRequest.SerializeToString,
            xion_dot_v1_dot_query__pb2.QueryWebAuthNVerifyRegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WebAuthNVerifyAuthenticate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xion.v1.Query/WebAuthNVerifyAuthenticate',
            xion_dot_v1_dot_query__pb2.QueryWebAuthNVerifyAuthenticateRequest.SerializeToString,
            xion_dot_v1_dot_query__pb2.QueryWebAuthNVerifyAuthenticateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
