# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from xion.v1 import tx_pb2 as xion_dot_v1_dot_tx__pb2


class MsgStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Send = channel.unary_unary(
                '/xion.v1.Msg/Send',
                request_serializer=xion_dot_v1_dot_tx__pb2.MsgSend.SerializeToString,
                response_deserializer=xion_dot_v1_dot_tx__pb2.MsgSendResponse.FromString,
                _registered_method=True)
        self.MultiSend = channel.unary_unary(
                '/xion.v1.Msg/MultiSend',
                request_serializer=xion_dot_v1_dot_tx__pb2.MsgMultiSend.SerializeToString,
                response_deserializer=xion_dot_v1_dot_tx__pb2.MsgMultiSendResponse.FromString,
                _registered_method=True)
        self.SetPlatformPercentage = channel.unary_unary(
                '/xion.v1.Msg/SetPlatformPercentage',
                request_serializer=xion_dot_v1_dot_tx__pb2.MsgSetPlatformPercentage.SerializeToString,
                response_deserializer=xion_dot_v1_dot_tx__pb2.MsgSetPlatformPercentageResponse.FromString,
                _registered_method=True)


class MsgServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Send(self, request, context):
        """Send defines a method for sending coins from one account to another
        account.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MultiSend(self, request, context):
        """MultiSend defines a method for sending coins from some accounts to other
        accounts.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPlatformPercentage(self, request, context):
        """SetPlatformPercentage defines the method for updating the platform
        percentage fee
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MsgServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=xion_dot_v1_dot_tx__pb2.MsgSend.FromString,
                    response_serializer=xion_dot_v1_dot_tx__pb2.MsgSendResponse.SerializeToString,
            ),
            'MultiSend': grpc.unary_unary_rpc_method_handler(
                    servicer.MultiSend,
                    request_deserializer=xion_dot_v1_dot_tx__pb2.MsgMultiSend.FromString,
                    response_serializer=xion_dot_v1_dot_tx__pb2.MsgMultiSendResponse.SerializeToString,
            ),
            'SetPlatformPercentage': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPlatformPercentage,
                    request_deserializer=xion_dot_v1_dot_tx__pb2.MsgSetPlatformPercentage.FromString,
                    response_serializer=xion_dot_v1_dot_tx__pb2.MsgSetPlatformPercentageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xion.v1.Msg', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xion.v1.Msg', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Msg(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xion.v1.Msg/Send',
            xion_dot_v1_dot_tx__pb2.MsgSend.SerializeToString,
            xion_dot_v1_dot_tx__pb2.MsgSendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MultiSend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xion.v1.Msg/MultiSend',
            xion_dot_v1_dot_tx__pb2.MsgMultiSend.SerializeToString,
            xion_dot_v1_dot_tx__pb2.MsgMultiSendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPlatformPercentage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xion.v1.Msg/SetPlatformPercentage',
            xion_dot_v1_dot_tx__pb2.MsgSetPlatformPercentage.SerializeToString,
            xion_dot_v1_dot_tx__pb2.MsgSetPlatformPercentageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
