# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xion/globalfee/v1/query.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'xion/globalfee/v1/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from xion.globalfee.v1 import genesis_pb2 as xion_dot_globalfee_dot_v1_dot_genesis__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dxion/globalfee/v1/query.proto\x12\x11xion.globalfee.v1\x1a\x1fxion/globalfee/v1/genesis.proto\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\"\x14\n\x12QueryParamsRequest\"N\n\x13QueryParamsResponse\x12\x37\n\x06params\x18\x01 \x01(\x0b\x32\x19.xion.globalfee.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params2\x83\x01\n\x05Query\x12z\n\x06Params\x12%.xion.globalfee.v1.QueryParamsRequest\x1a&.xion.globalfee.v1.QueryParamsResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/xion/globalfee/v1/paramsB\xb7\x01\n\x15\x63om.xion.globalfee.v1B\nQueryProtoP\x01Z,github.com/burnt-labs/xion/x/globalfee/types\xa2\x02\x03XGX\xaa\x02\x11Xion.Globalfee.V1\xca\x02\x11Xion\\Globalfee\\V1\xe2\x02\x1dXion\\Globalfee\\V1\\GPBMetadata\xea\x02\x13Xion::Globalfee::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xion.globalfee.v1.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.xion.globalfee.v1B\nQueryProtoP\001Z,github.com/burnt-labs/xion/x/globalfee/types\242\002\003XGX\252\002\021Xion.Globalfee.V1\312\002\021Xion\\Globalfee\\V1\342\002\035Xion\\Globalfee\\V1\\GPBMetadata\352\002\023Xion::Globalfee::V1'
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._loaded_options = None
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._serialized_options = b'\310\336\037\000'
  _globals['_QUERY'].methods_by_name['Params']._loaded_options = None
  _globals['_QUERY'].methods_by_name['Params']._serialized_options = b'\202\323\344\223\002\033\022\031/xion/globalfee/v1/params'
  _globals['_QUERYPARAMSREQUEST']._serialized_start=137
  _globals['_QUERYPARAMSREQUEST']._serialized_end=157
  _globals['_QUERYPARAMSRESPONSE']._serialized_start=159
  _globals['_QUERYPARAMSRESPONSE']._serialized_end=237
  _globals['_QUERY']._serialized_start=240
  _globals['_QUERY']._serialized_end=371
# @@protoc_insertion_point(module_scope)
