# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xion/v1/genesis.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'xion/v1/genesis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15xion/v1/genesis.proto\x12\x07xion.v1\x1a\x14gogoproto/gogo.proto\"?\n\x0cGenesisState\x12/\n\x13platform_percentage\x18\x01 \x01(\rR\x12platformPercentageB\x81\x01\n\x0b\x63om.xion.v1B\x0cGenesisProtoP\x01Z\'github.com/burnt-labs/xion/x/xion/types\xa2\x02\x03XXX\xaa\x02\x07Xion.V1\xca\x02\x07Xion\\V1\xe2\x02\x13Xion\\V1\\GPBMetadata\xea\x02\x08Xion::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xion.v1.genesis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.xion.v1B\014GenesisProtoP\001Z\'github.com/burnt-labs/xion/x/xion/types\242\002\003XXX\252\002\007Xion.V1\312\002\007Xion\\V1\342\002\023Xion\\V1\\GPBMetadata\352\002\010Xion::V1'
  _globals['_GENESISSTATE']._serialized_start=56
  _globals['_GENESISSTATE']._serialized_end=119
# @@protoc_insertion_point(module_scope)
