# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xion/v1/query.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'xion/v1/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13xion/v1/query.proto\x12\x07xion.v1\"z\n\"QueryWebAuthNVerifyRegisterRequest\x12\x12\n\x04\x61\x64\x64r\x18\x01 \x01(\tR\x04\x61\x64\x64r\x12\x1c\n\tchallenge\x18\x02 \x01(\tR\tchallenge\x12\x0e\n\x02rp\x18\x03 \x01(\tR\x02rp\x12\x12\n\x04\x64\x61ta\x18\x04 \x01(\x0cR\x04\x64\x61ta\"E\n#QueryWebAuthNVerifyRegisterResponse\x12\x1e\n\ncredential\x18\x01 \x01(\x0cR\ncredential\"\x9e\x01\n&QueryWebAuthNVerifyAuthenticateRequest\x12\x12\n\x04\x61\x64\x64r\x18\x01 \x01(\tR\x04\x61\x64\x64r\x12\x1c\n\tchallenge\x18\x02 \x01(\tR\tchallenge\x12\x0e\n\x02rp\x18\x03 \x01(\tR\x02rp\x12\x1e\n\ncredential\x18\x04 \x01(\x0cR\ncredential\x12\x12\n\x04\x64\x61ta\x18\x05 \x01(\x0cR\x04\x64\x61ta\")\n\'QueryWebAuthNVerifyAuthenticateResponse2\x82\x02\n\x05Query\x12u\n\x16WebAuthNVerifyRegister\x12+.xion.v1.QueryWebAuthNVerifyRegisterRequest\x1a,.xion.v1.QueryWebAuthNVerifyRegisterResponse\"\x00\x12\x81\x01\n\x1aWebAuthNVerifyAuthenticate\x12/.xion.v1.QueryWebAuthNVerifyAuthenticateRequest\x1a\x30.xion.v1.QueryWebAuthNVerifyAuthenticateResponse\"\x00\x42\x7f\n\x0b\x63om.xion.v1B\nQueryProtoP\x01Z\'github.com/burnt-labs/xion/x/xion/types\xa2\x02\x03XXX\xaa\x02\x07Xion.V1\xca\x02\x07Xion\\V1\xe2\x02\x13Xion\\V1\\GPBMetadata\xea\x02\x08Xion::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xion.v1.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.xion.v1B\nQueryProtoP\001Z\'github.com/burnt-labs/xion/x/xion/types\242\002\003XXX\252\002\007Xion.V1\312\002\007Xion\\V1\342\002\023Xion\\V1\\GPBMetadata\352\002\010Xion::V1'
  _globals['_QUERYWEBAUTHNVERIFYREGISTERREQUEST']._serialized_start=32
  _globals['_QUERYWEBAUTHNVERIFYREGISTERREQUEST']._serialized_end=154
  _globals['_QUERYWEBAUTHNVERIFYREGISTERRESPONSE']._serialized_start=156
  _globals['_QUERYWEBAUTHNVERIFYREGISTERRESPONSE']._serialized_end=225
  _globals['_QUERYWEBAUTHNVERIFYAUTHENTICATEREQUEST']._serialized_start=228
  _globals['_QUERYWEBAUTHNVERIFYAUTHENTICATEREQUEST']._serialized_end=386
  _globals['_QUERYWEBAUTHNVERIFYAUTHENTICATERESPONSE']._serialized_start=388
  _globals['_QUERYWEBAUTHNVERIFYAUTHENTICATERESPONSE']._serialized_end=429
  _globals['_QUERY']._serialized_start=432
  _globals['_QUERY']._serialized_end=690
# @@protoc_insertion_point(module_scope)
